name: CI/CD Pipeline for MuleSoft Applications

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mulesoft-1-jar
        path: target/*.jar

  deploy-to-mulesoft-2:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: mulesoft-1-jar

    - name: Set up Anypoint CLI
      run: |
        curl -O https://s3.amazonaws.com/anypoint-cli/anypoint-cli-3.8.9-windows64.zip
        tar -xf anypoint-cli-3.8.9-windows64.zip -C anypoint-cli
        set PATH=%PATH%;%cd%/anypoint-cli/bin

    - name: Deploy to MuleSoft-2
      run: |
        anypoint-cli/bin/anypoint-cli --username=%ANYPOINT_USERNAME% --password=%ANYPOINT_PASSWORD% runtime-mgr cloudhub-application deploy %APP_NAME_MULESOFT_2% ./target/mulesoft-1-app.jar --region %REGION%
      env:
        ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
        ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
        APP_NAME_MULESOFT_2: 'your-mulesoft-2-app-name'
        REGION: 'us-east-1'

  deploy-to-mulesoft-3:
    runs-on: windows-latest
    needs: deploy-to-mulesoft-2

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: mulesoft-1-jar

    - name: Set up Anypoint CLI
      run: |
        curl -O https://s3.amazonaws.com/anypoint-cli/anypoint-cli-3.8.9-windows64.zip
        tar -xf anypoint-cli-3.8.9-windows64.zip -C anypoint-cli
        set PATH=%PATH%;%cd%/anypoint-cli/bin

    - name: Deploy to MuleSoft-3
      run: |
        anypoint-cli/bin/anypoint-cli --username=%ANYPOINT_USERNAME% --password=%ANYPOINT_PASSWORD% runtime-mgr cloudhub-application deploy %APP_NAME_MULESOFT_3% ./target/mulesoft-1-app.jar --region %REGION%
      env:
        ANYPOINT_USERNAME: ${{ secrets.ANYPOINT2_USERNAME }}
        ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT2_PASSWORD }}
        APP_NAME_MULESOFT_3: 'your-mulesoft-3-app-name'
        REGION: 'us-east-1'

